In [1]:
# CREATE RANDOM DATA POINTS
import torch.nn as nn
import torch
from sklearn.datasets import make_blobs
import numpy

def blob_label(y, label, loc): # assign labels
    target = numpy.copy(y)
    for l in loc:
        target[y == l] = label
    return target


x_train, y_train = make_blobs(n_samples=40, n_features=2, cluster_std=1.5, shuffle=True)
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(blob_label(y_train, 0, [0]))
y_train = torch.FloatTensor(blob_label(y_train, 1, [1,2,3]))
x_test, y_test = make_blobs(n_samples=10, n_features=2, cluster_std=1.5, shuffle=True)
x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(blob_label(y_test, 0, [0]))
y_test = torch.FloatTensor(blob_label(y_test, 1, [1,2,3]))


In [2]:
y_train

tensor([1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        1., 1., 0., 1.])

In [3]:
class Feedforward(torch.nn.Module):
        def __init__(self, input_size, hidden_size):
            super(Feedforward, self).__init__()
            self.input_size = input_size
            self.hidden_size  = hidden_size
            self.fc1 = torch.nn.Linear(self.input_size, self.hidden_size)
            self.relu = torch.nn.ReLU()
            self.fc2 = torch.nn.Linear(self.hidden_size, 1)
            self.sigmoid = torch.nn.Sigmoid()
        def forward(self, x):
            hidden = self.fc1(x)
            relu = self.relu(hidden)
            output = self.fc2(relu)
            output = self.sigmoid(output)
            return output

In [4]:
model = Feedforward(2, 10)
criterion = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)
model

Feedforward(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=10, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [5]:
model.eval()
y_pred = model(x_test)
before_train = criterion(y_pred.squeeze(), y_test)
print('Test loss before training' , before_train.item())
y_pred

Test loss before training 0.8845343589782715


tensor([[0.6240],
        [0.6731],
        [0.8136],
        [0.5457],
        [0.6481],
        [0.7278],
        [0.5683],
        [0.5586],
        [0.6140],
        [0.7982]], grad_fn=<SigmoidBackward0>)

In [6]:
model.train()
epoch = 2000
for epoch in range(epoch):
    optimizer.zero_grad()
    # Forward pass
    y_pred = model(x_train)
    # Compute Loss
    loss = criterion(y_pred.squeeze(), y_train)
   
    print('Epoch {}: train loss: {}'.format(epoch, loss.item()))
    # Backward pass
    loss.backward()
    optimizer.step()

Epoch 0: train loss: 0.8636641502380371
Epoch 1: train loss: 0.8431320190429688
Epoch 2: train loss: 0.8238003849983215
Epoch 3: train loss: 0.8055909872055054
Epoch 4: train loss: 0.7884200811386108
Epoch 5: train loss: 0.7722110748291016
Epoch 6: train loss: 0.7568933367729187
Epoch 7: train loss: 0.742402195930481
Epoch 8: train loss: 0.7286781072616577
Epoch 9: train loss: 0.7156662940979004
Epoch 10: train loss: 0.7033165693283081
Epoch 11: train loss: 0.6915823221206665
Epoch 12: train loss: 0.6804208755493164
Epoch 13: train loss: 0.6697958707809448
Epoch 14: train loss: 0.6597252488136292
Epoch 15: train loss: 0.6501171588897705
Epoch 16: train loss: 0.6409404277801514
Epoch 17: train loss: 0.6321665048599243
Epoch 18: train loss: 0.6237689256668091
Epoch 19: train loss: 0.6157230138778687
Epoch 20: train loss: 0.6080060005187988
Epoch 21: train loss: 0.600601315498352
Epoch 22: train loss: 0.5935879945755005
Epoch 23: train loss: 0.5868390798568726
Epoch 24: train loss: 0.5803

In [7]:
model.eval()
y_pred = model(x_test)
after_train = criterion(y_pred.squeeze(), y_test) 
print('Test loss after Training' , after_train.item())

Test loss after Training 3.8493354320526123


In [8]:
y_pred

tensor([[0.0161],
        [0.9866],
        [1.0000],
        [0.9708],
        [0.1587],
        [0.9981],
        [0.0484],
        [0.9778],
        [0.9907],
        [0.9999]], grad_fn=<SigmoidBackward0>)

In [9]:
y_test

tensor([1., 0., 0., 1., 1., 0., 1., 1., 1., 0.])