In [3]:
import torch
import numpy as np

In [11]:
data = [[1,2], [3,4]]
x_data= torch.tensor(data)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_data

tensor([[1, 2],
        [3, 4]])

In [10]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [12]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8033, 0.5562],
        [0.3124, 0.5508]]) 



In [15]:
shape = (2, 5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.9749, 0.0974, 0.3843, 0.9430, 0.4762],
        [0.6526, 0.7095, 0.4533, 0.9838, 0.4809]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 



In [49]:
tensor = torch.ones(4,4)
tensor[:,1].sub_(5)
tensor[1,:].sub_(5)
tensor

tensor([[ 1., -4.,  1.,  1.],
        [-4., -9., -4., -4.],
        [ 1., -4.,  1.,  1.],
        [ 1., -4.,  1.,  1.]])