In [1]:
import torch.nn as nn
import torch
from sklearn.datasets import make_blobs
import numpy

In [13]:
def blob_label(y, label, loc): # assign labels
    target = numpy.copy(y)
    for l in loc:
        target[y == l] = label
    return target


x_train, y_train = make_blobs(n_samples=40, n_features=2, cluster_std=1.5, shuffle=True)
y_train

array([0, 1, 2, 1, 0, 0, 1, 2, 2, 0, 0, 0, 2, 1, 2, 2, 1, 0, 0, 1, 2, 1,
       0, 1, 0, 0, 1, 2, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 1, 2])

In [16]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(blob_label(y_train, 0, [0]))
#y_train = torch.FloatTensor(y_train)
y_train

tensor([0., 1., 2., 1., 0., 0., 1., 2., 2., 0., 0., 0., 2., 1., 2., 2., 1., 0.,
        0., 1., 2., 1., 0., 1., 0., 0., 1., 2., 2., 0., 2., 0., 0., 1., 2., 1.,
        1., 2., 1., 2.])

In [35]:
y_train = torch.FloatTensor(blob_label(y_train, 1, [1,2,3]))
y_train

tensor([0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
        0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
        1., 1., 1., 1.])

In [36]:
x_test, y_test = make_blobs(n_samples=10, n_features=2, cluster_std=1.5, shuffle=True)
x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(blob_label(y_test, 0, [0]))
y_test = torch.FloatTensor(blob_label(y_test, 1, [1,2,3]))